### ISSUE TITLE
Plugin not returning random blocks

### ISSUE THREAD

**Issue by CSilvaGit** [vipzhicheng/logseq-plugin-random-block#1]
I've installed the plugin, closed and reopened LogSeq, and reproduced the example from your gif but I can seem to get it to return random blocks.

I've created these blocks:

- aaa #[[random test]]
- bbb #[[random test]]
- ccc #[[random test]]
- ddd #[[random test]]

- Test {{renderer random-block, #[[random test]], 2}}

And after I click the refresh icon I get nothing.

Can you help me figure out what might be wrong?

**Comment by vipzhicheng** [comment]
It works for me and I can not reproduce this issue on my MacOS.

**Comment by CSilvaGit** [comment]
Even after one year and 7 months, that wasn't very helpful...But thanks anyway!
